---
- name:
  hosts: aws
  become: true
  tasks:
  - name: Update apt
    ansible.builtin.package:
      upgrade: true
      update_cache: true
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: present
    notify: Reload nginx
  handlers:
  - name: Reload nginx
    ansible.builtin.service:
      name: nginx
      state: reloaded
      enabled: true
